### ISSUE TITLE
impossible to clone repo, timeout

### ISSUE THREAD

**Issue by asavah** [hardkernel/linux#307]
Having severe problems to clone this repo.
100Mbit inet, no problems at all cloning large repos from github, **except this one**.
I have tried cloning on my vultr VPS in the US - same result, so it's not my internet, my os and not github.
Having outdated, buggy and vulnerable (unpatched CVEs)  kernel for odroid-c2 is apparently not enough, now we can't clone the repo too.
**Good job hardkernel!**
Please solve the issue or contact github staff for assistance.

```
 GIT_CURL_VERBOSE=1 git clone https://github.com/hardkernel/linux.git
Cloning into 'linux'...
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: businessCategory=Private Organization; jurisdictionC=US; jurisdictionST=Delaware; serialNumber=5157550; street=88 Colin P Kelly, Jr Street; postalCode=94107; C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Mar 10 00:00:00 2016 GMT
*  expire date: May 17 12:00:00 2018 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*  SSL certificate verify ok.
> GET /hardkernel/linux.git/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.13.3
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-GB, en;q=0.9, *;q=0.8
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: EA34:10BAD:3EC1BCF:6B1FEB3:5974C044
< X-Frame-Options: DENY
<
* transfer closed with outstanding read data remaining
* Curl_http_done: called premature == 1
* Closing connection 0
fatal: unable to access 'https://github.com/hardkernel/linux.git/': transfer closed with outstanding read data remaining
```

**Comment by mdrjr** [comment]
Enlight me on how your failure to access github is somehow our fault.


Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: asavah <notifications@github.com> Data: 23/07/17  12:39  (GMT-03:00) Para: hardkernel/linux <linux@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Assunto: [hardkernel/linux] impossible to clone repo, timeout (#307) 
Having severe problems to clone this repo.

100Mbit inet, no problems at all cloning large repos from github, except this one.

I have tried cloning on my vultr VPS in the US - same result, so it's not my internet, my os and not github.

Having outdated, buggy and vulnerable (unpatched CVEs)  kernel for odroid-c2 is apparently not enough, now we can't clone the repo too.

Good job hardkernel!

Please solve the issue or contact github staff for assistance.
 GIT_CURL_VERBOSE=1 git clone https://github.com/hardkernel/linux.git
Cloning into 'linux'...
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: businessCategory=Private Organization; jurisdictionC=US; jurisdictionST=Delaware; serialNumber=5157550; street=88 Colin P Kelly, Jr Street; postalCode=94107; C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Mar 10 00:00:00 2016 GMT
*  expire date: May 17 12:00:00 2018 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*  SSL certificate verify ok.
> GET /hardkernel/linux.git/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.13.3
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-GB, en;q=0.9, *;q=0.8
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: EA34:10BAD:3EC1BCF:6B1FEB3:5974C044
< X-Frame-Options: DENY
<
* transfer closed with outstanding read data remaining
* Curl_http_done: called premature == 1
* Closing connection 0
fatal: unable to access 'https://github.com/hardkernel/linux.git/': transfer closed with outstanding read data remaining


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hardkernel/linux","title":"hardkernel/linux","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hardkernel/linux"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"impossible to clone repo, timeout (#307)"}],"action":{"name":"View Issue","url":"https://github.com/hardkernel/linux/issues/307"}}}

**Comment by ardje** [comment]
It also might be better not to use https: as a git url.
It is recomended against. Use the normal ssh and see if you get a timeout
then.
Even in that case, it's still github that's giving you a timeout.
The only thing to do then is to wait until github has sorted out it's
problems.
So one thing that is really bugging me is your conclusion that it's not
github.

**Comment by asavah** [comment]
@ardje My conclusion that it's not github is because a can clone every other HUGE repo from github via https and ssh I've tried, to make sure thats the issue is with _this_ repo _only_.
It doesn't matter, with ssh I was getting timeouts too, 
both https and ssh work now tho, tried from different locations. Thus I'm closing this as resolved.
I reported this here and and not github itself because _only_ this repo was having issues.


@mdrjr Is my english that bad? or may be you didn't read the issue? As I said  I don't have connectivity issues with github, none at all, for troubleshooting sake I've tried cloning this bunch of  ... ok, let's call it code ... from several servers located in different parts of the world, with different OSes and git client versions, it always failed. Period.
Only this damn repo was failing, and it's your responsibility as mantainer to confirm/deny the problem and contact github staff.
You attitude won't help hardkernel hardware with stillborn and braindead kernels.
