### ISSUE TITLE
Booting kenel 3.12 on XU

### ISSUE THREAD

**Issue by roosemberth** [hardkernel/linux#33]
Is there any file documenting procedures or ofering any kind of documentation?

**Comment by mdrjr** [comment]
because of the limited support on kernel.. no there's no documentation.

A guide and dirty guide would be.

Copy zImage or uImage to fat partition as well the dtb file.

Change boot.ini to load the dtb file into ram on a adress above the dtb uinitrd
use bootz kernel_address uinitrd_address dtb_address
for zImage
or
bootm for uImage

**Comment by roosemberth** [comment]
Thanks!
